server:
  port: 8080

kakao:
  client-id: d599c4d57b813341c889a31b401d7f31
  redirect-uri: http://localhost:3000/auth/callback

spring:
  servlet:
    encoding:
      charset: UTF-8
      force: true

  datasource:
    url: jdbc:mysql://localhost:3306/hackathon_db
      ?useSSL=false
      &allowPublicKeyRetrieval=true
      &serverTimezone=Asia/Seoul
      &characterEncoding=UTF-8
    username: wooh
    password: dngur1213!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    property-naming-strategy: SNAKE_CASE   # 응답 필드 스네이크케이스

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
