server:
  port: 8080

spring:
  servlet:
    encoding:
      charset: UTF-8
      force: true

  datasource:
    url: jdbc:mysql://mutsa-db.c70gmyqsgx70.ap-northeast-2.rds.amazonaws.com:3306/hackathon_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useUnicode=true&connectionCollation=utf8mb4_unicode_ci
    username: wooh
    password: dngur1213
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        connection:
          characterEncoding: UTF-8
          useUnicode: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.security: DEBUG


